### ISSUE TITLE
Minecraft 10 Ampersands/Updating Minecraft 10

### ISSUE THREAD

**Issue by blank3times** [ewanhowell5195/MinecraftTitleGenerator#100]
Various questions, but I'm classifying this as an "extra characters" thing.

I was just watching the new Minecraft Monthly and realized that they've had some changes to MC-10 (not in the logo, but in other uses) for at least half a year now with a new E, F, 3, C, ?, and &.

Changing the font by now for the E, F, and 3 is just barely doable ('Only' 105 textures and overlays!) and I wouldn't necessarily recommend.

However, the logo has now had changed the ampersand 3 times for a total of 4. (V&P, C&C, T&T, and then the new one which is in MCD: Chills & Thrills). Since these all appear in game logos, would there be a way to make a supplement font that is solely ampersands, and how?

**Comment by ewanhowell5195** [comment]
i will not be changing the font.

**Comment by blank3times** [comment]
Correction: Add a supplement font with just ampersands

**Comment by ewanhowell5195** [comment]
you are free to do that. i added support for font variants recently

**Comment by ewanhowell5195** [comment]
https://github.com/ewanhowell5195/MinecraftTitleGenerator/blob/main/README.md#font-variants

updated the readme with info on font variants

**Comment by blank3times** [comment]
Thank you, that's helpful.
