### ISSUE TITLE
Blockbench fonts and textures not loading. 

### ISSUE THREAD

**Issue by JesseGamingYT6** [ewanhowell5195/MinecraftTitleGenerator#110]
Wen logging in the fonts and textures won't work, it's asking for checking the connection, also the "fonts.json" file, I still don't get the issue but Pls fix this issue. 🙏

**Comment by ewanhowell5195** [comment]
please make sure you are on the latest plugin version 1.3.1

this is not an issue with the plugin itself

**Comment by JesseGamingYT6** [comment]
How do I update it?
