### ISSUE TITLE
Bottom line stretching leads to oversized gui border

### ISSUE THREAD

**Issue by blank3times** [ewanhowell5195/MinecraftTitleGenerator#111]
![image](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/105398129/9369e9a3-df6e-477a-88a2-8a8c93b88bbd)

The border of the flat gui font is extruded as always, but since the font is flat and the border isn't, the border ends up oversized. It's adding to the sizes which ends up very funky.

If the border's Z size were 3 and the text 0 for the flat fonts it would appear less awkward.

**Comment by ewanhowell5195** [comment]
This is a bug with the plugin itself and has been fixed in 1.3.3. Please wait for that release to be merged.
