### ISSUE TITLE
Bevel overlay for Minecraft ten

### ISSUE THREAD

**Issue by MiffenKop** [ewanhowell5195/MinecraftTitleGenerator#114]
J, V, {, and } are sized incorrectly
![image_2023-10-15_113111996](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/102834924/f403079d-fe3f-47aa-ba96-531298622d17)

**Comment by ewanhowell5195** [comment]
can you provide the steps to recreate the issue
