### ISSUE TITLE
Not An Issue just an suggestion

### ISSUE THREAD

**Issue by Olpence** [ewanhowell5195/MinecraftTitleGenerator#150]
Add these fonts!

Cant list downloads but heres the link to them all:
https://mctitles.com/download-fonts/

**Comment by ewanhowell5195** [comment]
i do not take suggestions. if you want something, make it, and submit it.
https://github.com/ewanhowell5195/MinecraftTitleGenerator?tab=readme-ov-file#how-to-make-a-submission
