### ISSUE TITLE
Creating a title does not create a model on Flathub Version

### ISSUE THREAD

**Issue by Dromaeosaurs** [ewanhowell5195/MinecraftTitleGenerator#160]
OS: Manjaro Linux (Arch based distro)
After recent electron 30 update, AUR version of blockbench stopped working, so I switched to flathub one (flathub version is official).
Creating a title creates only a texture, no 3d model has been made (even in preview,debug text and render).
UV sides are visible in texture preview
It seems to be an app-only issue, it works flawlessly in browser.
After waiting 20 minutes for electron 26 to build, I've learned that appimage version also works fine.
It's probably related to `three.min.js:6`?

I tried: 
- uninstalling electron,electron 30 etc.
- building electron 26 from source
- reinstalling blockbench and the plugin
- updating OS
- rebooting
- uninstalling other plugins

Here's some pics:
![obraz](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/82401427/444941a1-3f69-416b-9c5d-8446e3f5b6dd)

![obraz](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/82401427/1fe104c4-4797-49e4-a4fd-1fdbcee05742)

Sorry for such little information, I'm not a programmer
If you are too busy, then put out a statement that says: "switch 2 appimage because flathub brokie xd"

**Comment by ewanhowell5195** [comment]
This has got nothing to do with my plugin, please go to blockbench. https://github.com/JannisX11/blockbench/issues
