### ISSUE TITLE
letter "Д" texture in minecraft five bold cyrillic font is not displayed correctly

### ISSUE THREAD

**Issue by jackeyrolz** [ewanhowell5195/MinecraftTitleGenerator#174]
![issue](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/151940887/3eabae81-b441-45dc-9955-a7fc213600a0)

**Comment by jackeyrolz** [comment]
![newissue](https://github.com/user-attachments/assets/6318308a-59b8-4afa-bd84-b62dd087ee0d)
![newissue1](https://github.com/user-attachments/assets/6be6e31d-2f54-4a34-8def-f87e3d031cba)
well, still not fixed :_)

**Comment by ewanhowell5195** [comment]
It is fixed

**Comment by blank3times** [comment]
Characters tend to only show one face on this tool (exception default M), even if they don't in the source material (e.g., the whole Dungeons font).
