### ISSUE TITLE
Texture suggestions

### ISSUE THREAD

**Issue by oliviathevampire** [ewanhowell5195/MinecraftTitleGenerator#19]
- Honey
- Bricks
- Metal
- Candy
- Ice
- Pumpkin
- Redstone

**Comment by oliviathevampire** [comment]
Maybe different types of metals? like bronze, tin

**Comment by oliviathevampire** [comment]
* Crafting table
* Some kind of stones?

**Comment by oliviathevampire** [comment]
Trails & Tales update texture

**Comment by ewanhowell5195** [comment]
Closing as I do not want requests/suggestions made through issues
