### ISSUE TITLE
Minecraft Legends font?

### ISSUE THREAD

**Issue by oliviathevampire** [ewanhowell5195/MinecraftTitleGenerator#25]
Would love a font which has letters kinda like minecraft legends, could be super interesting

**Comment by ewanhowell5195** [comment]
that font wont really work in this plugin, since the characters are designed specifically for the logo, and do not work out of that order, so I will be closing this issue

**Comment by AnolXD** [comment]
So, even if you have a font from which we can make character models https://fontstruct.com/fontstructions/show/2254559/legendary-18
It can't be added because of the capital letters or the letters W, M?

**Comment by ewanhowell5195** [comment]
if you have a font with different upper and lowercase letters, that needs to be made as two fonts
