### ISSUE TITLE
Cyrillic fonts support

### ISSUE THREAD

**Issue by thesh1xx** [ewanhowell5195/MinecraftTitleGenerator#37]
Here the minecraft ten and five fonts with cyrillic symbols included
[Minecraft Cyrillic Fonts.zip](https://github.com/ewanhowell5195/MinecraftTitleGenerator/files/11727590/Minecraft.Cyrillic.Fonts.zip)

**Comment by ewanhowell5195** [comment]
follow the guide in the readme to submit fonts
