### ISSUE TITLE
I want to make cyrillic font

### ISSUE THREAD

**Issue by timaaos** [ewanhowell5195/MinecraftTitleGenerator#44]
README said to add an issue if i want to use other characters, than latin alphabet.  
![image](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/75538611/82788e16-ad79-4c01-9a38-728377f93977)  
I will be using these characters:  
```
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ
```

**Comment by ewanhowell5195** [comment]
you can make that that is fine

**Comment by timaaos** [comment]
thx

**Comment by timaaos** [comment]
by the way, can i just extend minecraft-ten?

**Comment by ewanhowell5195** [comment]
no. make it its own font for maximum texture compatibility

**Comment by timaaos** [comment]
okay, i have copied characters, that look same in latin and in cyrillic:
```
АВЕКМНОРСТХ (cyr) <- ABEKMHOPCTX (lat)
```

**Comment by xlifi** [comment]
I actually been making cyrilllic font for last week or so
It's almost ready now.
