### ISSUE TITLE
[Bug] Unable to re-open Minecraft Title Generator Projects, and the widget for rendering the text doesn't show up

### ISSUE THREAD

**Issue by BookWyrm114** [ewanhowell5195/MinecraftTitleGenerator#74]
Upon reopening a Minecraft Title Generator project, the entire screen is blank, and when clicking on the arrows in the bottom left or right corner, which seems to fix the issue, the project now shows up as completely empty:

<img width="1908" alt="image" src="https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/79489385/9c972f9f-3438-40a2-b4b5-80162e3b6c0d">
<img width="1906" alt="image" src="https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/79489385/c0aa8b3c-921c-4136-b495-22bd905669f2">

Also, when attempting to render text, the widget with the controls for doing so don't appear:

<img width="1903" alt="image" src="https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/79489385/dd69e881-7a1b-418f-9812-2886b0d8a35f">

**Comment by ewanhowell5195** [comment]
unable to reproduce. could you send your project file, and try factory resetting blockbench

**Comment by BookWyrm114** [comment]
just factory reset blockbench and everything works fine now
